### PR TITLE
Add Node.JS and tldr-pages client

### PR DESCRIPTION
**Pull request by sbrl**
[tldr-pages](https://tldr.sh/) is a brilliant community-run resource for both beginner and advanced terminal users alike. It lets you get some quick examples on how to use any command. This PR adds Node.JS, and the official tldr-pages command-line client.

### CODE REVIEW

**Comment by Epictek** [comment]
I would say yes to node.js but unsure about installing npm global packages, most people recommend against that!

P.S ignore the CI build was playing with travis.

**Comment by sbrl** [comment]
Ah, I see. You're right to be concerned, but in this case it's a program that's written in Node.JS, and distributed through npm. It's not actually a library that you should install locally.

**Comment by Epictek** [comment]
Yes but it has a lot of dependencies for something that just displays man pages (a pet peeve of mine with node apps). A lot of people won't use the package so it makes more sense for individual users to install it in their home so they can keep it updated rather then relying on admins to issue npm update (or whatever the command to update node packages is).

Another advantage of this being is the tldr command would work on any machine with their home dir mounted. I'd suggest making a new PR for node.js and we can keep this one open for futher discussion if you would like.

**Comment by sbrl** [comment]
Ah, ok. There are tons of other clients, so maybe something a bit lighter, say, like the C++ client would work better?

**Comment by Epictek** [comment]
Ideally a client that has a Fedora repo?

**Comment by Epictek** [comment]
Even better, We could change the default bashrc to have this. No need to install anything then!

```
function tldr() { curl -s https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/common/"$1.md" | mad -; }
```

**Comment by sbrl** [comment]
Hrm, that might be good. Don't think any of them do, though.

Ah, good try - but many commands are scattered across the different platform folders. The ones in the `common` folder have to be fully compatible with windows! At some point we'll be sorting that directory out because many of the pages in there aren't actually portable.

**Comment by Epictek** [comment]
https://github.com/raylee/tldr seems like the best client for our use case, doesn't require node and is lightweight

**Comment by sbrl** [comment]
Yeah! I'd download & test it though, just to make sure.

**Pull request closed without merging**
